server.port=8082
spring.application.name=pedido-service

spring.datasource.url=jdbc:h2:mem:pedidodb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info

# URL do serviço de produtos (comunicação entre microserviços)
produto.service.url=http://localhost:8081
usuario.service.url=http://localhost:8083
