server.port=8081
spring.application.name=produto-service

# H2 Database (embutido - zero configuração)
spring.datasource.url=jdbc:h2:mem:produtodb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
