server.port=8080
spring.application.name=api-gateway

# URLs dos microserviços — o gateway conhece todos
produto.service.url=http://localhost:8081
pedido.service.url=http://localhost:8082
usuario.service.url=http://localhost:8083

# Thymeleaf
spring.thymeleaf.cache=false
